[general]
# Exit directly after copy/save action
early-exit = true
# Select the tool on startup [possible values: pointer, crop, line, arrow, rectangle, text, marker, blur, brush]
initial-tool = "brush"
# Configure the command to be called on copy, for example `wl-copy`
copy-command = "wl-copy"
# Increase or decrease the size of the annotations
annotation-size-factor = 2
# Hide toolbars by default
default-hide-toolbars = false
# Font to use for text annotations
[font]
family = "Myriad Pro"

# custom colours for the colour palette
[color-palette]
first= "#ff2b2b"
second= "#ffd700"
third= "#ffff85"
fourth= "#55ff55"
fifth= "#87ceff"
custom= "#333333"
