# Recommended location for database
db_file            "~/.config/mpd/database"

# Music/Playlists
music_directory    "~/Music"
playlist_directory "~/.config/mpd/playlists"

# Uncomment to refresh the database whenever files in the music_directory are changed
auto_update "yes"

# Uncomment to enable the functionalities
state_file         "~/.local/state/mpd/state"

# alsa
audio_output {
        type          "alsa"
        name          "ALSA sound card"
}

# visualizer
audio_output {
    type                    "fifo"
    name                    "my_fifo"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}
